-- MovieUser Table
CREATE TABLE MovieUser (
    UserID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-generated primary key
    UserName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL,
    JoinDate DATE
);

-- UserList Table
CREATE TABLE USERLIST (
    USERID NUMBER(38, 0),            -- Foreign key to MOVIEUSER table
    LISTID NUMBER(38, 0),            -- Identifies the list (1, 2, 3 for each user)
    LISTNAME VARCHAR2(100 BYTE),     -- Name of the list
    PRIMARY KEY (USERID, LISTID),    -- Composite primary key
    CONSTRAINT FK_LIST_USER FOREIGN KEY (USERID) REFERENCES MOVIEUSER(USERID)
);

-- Movie Table
CREATE TABLE Movie (
    MovieID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-generated primary key
    Title VARCHAR2(255) NOT NULL,
    ReleaseDate DATE,
    Description VARCHAR2(4000),
    AverageRating DECIMAL(3, 2)
);

-- Reviews Table
CREATE TABLE Reviews (
    UserID INT,
    MovieID INT,
    UserRating INT CHECK (UserRating BETWEEN 1 AND 10),
    ReviewDescription VARCHAR2(4000),
    ReviewDate DATE,
    PRIMARY KEY (UserID, MovieID),
    FOREIGN KEY (UserID) REFERENCES MovieUser(UserID) ON DELETE CASCADE,
    FOREIGN KEY (MovieID) REFERENCES Movie(MovieID) ON DELETE CASCADE
);

-- ListMovies Table
CREATE TABLE ListMovies (
    UserID NUMBER(38, 0),
    ListID NUMBER(38, 0),
    MovieID NUMBER(38, 0),
    PRIMARY KEY (UserID, ListID, MovieID),  -- Composite primary key including UserID, ListID, and MovieID
    FOREIGN KEY (UserID, ListID) REFERENCES UserList(UserID, ListID) ON DELETE CASCADE,  -- Foreign key referencing composite key of UserList
    FOREIGN KEY (MovieID) REFERENCES Movie (MovieID)  -- Foreign key referencing Movie table (assuming Movie table exists)
);

-- Actor Table
CREATE TABLE Actor (
    ActorID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-generated primary key
    Name VARCHAR(100) NOT NULL,
    BirthDate DATE
);

-- Director Table
CREATE TABLE Director (
    DirectorID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-generated primary key
    Name VARCHAR(100) NOT NULL,
    BirthDate DATE
);

-- MovieActor Table
CREATE TABLE MovieActor (
    MovieID INT,
    ActorID INT,
    Role VARCHAR(100),
    PRIMARY KEY (MovieID, ActorID),
    FOREIGN KEY (MovieID) REFERENCES Movie(MovieID) ON DELETE CASCADE,
    FOREIGN KEY (ActorID) REFERENCES Actor(ActorID) ON DELETE CASCADE
);

-- MovieDirector Table
CREATE TABLE MovieDirector (
    MovieID INT,
    DirectorID INT,
    Role VARCHAR(100),
    PRIMARY KEY (MovieID, DirectorID),
    FOREIGN KEY (MovieID) REFERENCES Movie(MovieID) ON DELETE CASCADE,
    FOREIGN KEY (DirectorID) REFERENCES Director(DirectorID) ON DELETE CASCADE
);

-- Genre Table
CREATE TABLE Genre (
    GenreID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-generated primary key
    GenreType VARCHAR(50) NOT NULL
);

-- MovieGenre Table
CREATE TABLE MovieGenre (
    GenreID INT,
    MovieID INT,
    PRIMARY KEY (GenreID, MovieID),
    FOREIGN KEY (GenreID) REFERENCES Genre(GenreID) ON DELETE CASCADE,
    FOREIGN KEY (MovieID) REFERENCES Movie(MovieID) ON DELETE CASCADE
);

CREATE OR REPLACE TRIGGER TRG_CREATE_USER_LISTS
AFTER INSERT ON MOVIEUSER
FOR EACH ROW
BEGIN
  -- Insert "Favorites" list with LISTID = 1
  INSERT INTO USERLIST (USERID, LISTID, LISTNAME)
  VALUES (:NEW.USERID, 1, 'Favorites');
  
  -- Insert "Watch Later" list with LISTID = 2
  INSERT INTO USERLIST (USERID, LISTID, LISTNAME)
  VALUES (:NEW.USERID, 2, 'Watch Later');
  
  -- Insert "Reviewed" list with LISTID = 3
  INSERT INTO USERLIST (USERID, LISTID, LISTNAME)
  VALUES (:NEW.USERID, 3, 'Reviewed');
END;
/

INSERT INTO Genre (GenreType) VALUES ('Action');
INSERT INTO Genre (GenreType) VALUES ('Adventure');
INSERT INTO Genre (GenreType) VALUES ('Animation');
INSERT INTO Genre (GenreType) VALUES ('Comedy');
INSERT INTO Genre (GenreType) VALUES ('Crime');
INSERT INTO Genre (GenreType) VALUES ('Drama');
INSERT INTO Genre (GenreType) VALUES ('Fantasy');
INSERT INTO Genre (GenreType) VALUES ('Horror');
INSERT INTO Genre (GenreType) VALUES ('Mystery');
INSERT INTO Genre (GenreType) VALUES ('Romance');
INSERT INTO Genre (GenreType) VALUES ('Sci-Fi');
INSERT INTO Genre (GenreType) VALUES ('Thriller');
INSERT INTO Genre (GenreType) VALUES ('Documentary');
INSERT INTO Genre (GenreType) VALUES ('Biography');
INSERT INTO Genre (GenreType) VALUES ('Family');
INSERT INTO Genre (GenreType) VALUES ('Musical');
INSERT INTO Genre (GenreType) VALUES ('Western');
INSERT INTO Genre (GenreType) VALUES ('War');
INSERT INTO Genre (GenreType) VALUES ('Sport');


INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('Forrest Gump', TO_DATE('1994-07-06', 'YYYY-MM-DD'), 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an extraordinary, and highly unintelligent, life.', 8.8, EMPTY_BLOB());

INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('Inception', TO_DATE('2010-07-16', 'YYYY-MM-DD'), 'A thief who enters the dreams of others to steal secrets from their subconscious is given the inverse task of planting an idea into the mind of a CEO.', 8.8, EMPTY_BLOB());

INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('The Matrix', TO_DATE('1999-03-31', 'YYYY-MM-DD'), 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.', 8.7, EMPTY_BLOB());

INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('Goodfellas', TO_DATE('1990-09-19', 'YYYY-MM-DD'), 'The story of Henry Hill and his life in the Mafia, covering his relationship with his wife and his mafia dealings, all the way through his testimony against his associates.', 8.7, EMPTY_BLOB());

INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('The Lord of the Rings: The Return of the King', TO_DATE('2003-12-17', 'YYYY-MM-DD'), 'Gandalf and Aragorn lead the World of Men against Sauron''s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.', 8.9, EMPTY_BLOB());

INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('Star Wars: Episode IV - A New Hope', TO_DATE('1977-05-25', 'YYYY-MM-DD'), 'Luke Skywalker embarks on a perilous journey to rescue Princess Leia and destroy the Death Star, a space station capable of obliterating entire planets.', 8.6, EMPTY_BLOB());

INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('The Silence of the Lambs', TO_DATE('1991-02-14', 'YYYY-MM-DD'), 'A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.', 8.6, EMPTY_BLOB());

INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('Schindler''s List', TO_DATE('1993-12-15', 'YYYY-MM-DD'), 'In German-occupied Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.', 9.0, EMPTY_BLOB());

INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('Pulp Fiction', TO_DATE('1994-10-14', 'YYYY-MM-DD'), 'The lives of two mob hitmen, a boxer, a gangster''s wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 8.9, EMPTY_BLOB());

INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('Fight Club', TO_DATE('1999-10-15', 'YYYY-MM-DD'), 'An insomniac office worker and a soap salesman build a global organization to help vent male aggression.', 8.8, EMPTY_BLOB());

INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('The Lion King', TO_DATE('1994-06-24', 'YYYY-MM-DD'), 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.', 8.5, EMPTY_BLOB());

INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('The Dark Knight Rises', TO_DATE('2012-07-20', 'YYYY-MM-DD'), 'Eight years after the Joker''s reign of terror, Batman is forced out of hiding when a new terrorist mastermind, Bane, arrives in Gotham City to destroy it.', 8.4, EMPTY_BLOB());

INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('Interstellar', TO_DATE('2014-11-07', 'YYYY-MM-DD'), 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.', 8.6, EMPTY_BLOB());

INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('Parasite', TO_DATE('2019-05-30', 'YYYY-MM-DD'), 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the poor Kim clan.', 8.6, EMPTY_BLOB());

INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('The Prestige', TO_DATE('2006-10-20', 'YYYY-MM-DD'), 'Two magicians engage in a bitter rivalry, with each one trying to best the other by staging the ultimate illusion.', 8.5, EMPTY_BLOB());

INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('The Shawshank Redemption', TO_DATE('1994-09-22', 'YYYY-MM-DD'), 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 9.3, EMPTY_BLOB());

INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('The Departed', TO_DATE('2006-10-06', 'YYYY-MM-DD'), 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in Boston.', 8.5, EMPTY_BLOB());

INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('The Green Mile', TO_DATE('1999-12-10', 'YYYY-MM-DD'), 'The lives of guards on death row are affected by one of their charges: a black man accused of murdering two white girls who has a miraculous gift.', 8.6, EMPTY_BLOB());

INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('Gladiator', TO_DATE('2000-05-05', 'YYYY-MM-DD'), 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.', 8.5, EMPTY_BLOB());

INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('The Godfather: Part II', TO_DATE('1974-12-12', 'YYYY-MM-DD'), 'The early life and career of Vito Corleone in 1920s Sicily and 1930s New York are depicted, alongside his son Michael''s journey to power in the 1950s.', 9.0, EMPTY_BLOB());

INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('Casablanca', TO_DATE('1942-11-26', 'YYYY-MM-DD'), 'A cynical American expatriate struggles to decide whether or not he should help his former lover and her fugitive husband escape French Morocco during World War II.', 8.5, EMPTY_BLOB());

INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('The Godfather: Part III', TO_DATE('1990-12-25', 'YYYY-MM-DD'), 'Michael Corleone seeks to legitimize his family''s business while dealing with personal and political turmoil.', 7.6, EMPTY_BLOB());

INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('Citizen Kane', TO_DATE('1941-05-01', 'YYYY-MM-DD'), 'Following the death of a publishing tycoon, news reporters scramble to uncover the meaning of his final utterance.', 8.3, EMPTY_BLOB());

INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('The Big Lebowski', TO_DATE('1998-03-06', 'YYYY-MM-DD'), 'Jeff "The Dude" Lebowski, mistaken for a millionaire of the same name, seeks restitution for his ruined rug and enlists his bowling buddies to help get it.', 8.1, EMPTY_BLOB());

INSERT INTO movie (title, releasedate, description, averagerating, movie_picture) 
VALUES
('One Flew Over the Cuckoo''s Nest', TO_DATE('1975-11-19', 'YYYY-MM-DD'), 'A criminal pleads insanity and is admitted to a mental institution, where he rebels against the oppressive nurse and rallies the patients.', 8.7, EMPTY_BLOB());

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'Forrest Gump' AND g.genretype IN ('Drama', 'Romance');

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'Inception' AND g.genretype IN ('Action', 'Adventure', 'Sci-Fi');

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'The Matrix' AND g.genretype IN ('Action', 'Sci-Fi');

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'Goodfellas' AND g.genretype IN ('Crime', 'Drama');

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'The Lord of the Rings: The Return of the King' AND g.genretype IN ('Action', 'Adventure', 'Drama', 'Fantasy');

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'Star Wars: Episode IV - A New Hope' AND g.genretype IN ('Action', 'Adventure', 'Fantasy', 'Sci-Fi');

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'The Silence of the Lambs' AND g.genretype IN ('Crime', 'Drama', 'Horror', 'Thriller');

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'Schindler''s List' AND g.genretype IN ('Biography', 'Drama', 'History');

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'Pulp Fiction' AND g.genretype IN ('Crime', 'Drama');

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'Fight Club' AND g.genretype IN ('Drama');

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'The Lion King' AND g.genretype IN ('Animation', 'Drama', 'Family');

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'The Dark Knight Rises' AND g.genretype IN ('Action', 'Crime', 'Drama', 'Thriller');

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'Interstellar' AND g.genretype IN ('Adventure', 'Drama', 'Sci-Fi');

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'Parasite' AND g.genretype IN ('Drama', 'Thriller');

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'The Prestige' AND g.genretype IN ('Drama', 'Mystery', 'Sci-Fi');

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'The Shawshank Redemption' AND g.genretype IN ('Drama');

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'The Departed' AND g.genretype IN ('Crime', 'Drama', 'Thriller');

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'The Green Mile' AND g.genretype IN ('Drama', 'Fantasy');

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'Gladiator' AND g.genretype IN ('Action', 'Adventure', 'Drama');

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'The Godfather: Part II' AND g.genretype IN ('Crime', 'Drama');

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'Casablanca' AND g.genretype IN ('Drama', 'Romance', 'War');

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'The Godfather: Part III' AND g.genretype IN ('Crime', 'Drama');

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'Citizen Kane' AND g.genretype IN ('Drama', 'Mystery');

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'The Big Lebowski' AND g.genretype IN ('Comedy', 'Crime', 'Drama');

INSERT INTO moviegenre (movieid, genreid)
SELECT m.movieid, g.genreid
FROM movie m, genre g
WHERE m.title = 'One Flew Over the Cuckoo''s Nest' AND g.genretype IN ('Drama');

COMMIT;